temp skip big tests
Signed-off-by: pbio <10051819+paulbalaji@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -186,221 +186,221 @@ jobs:
             exit 1
           fi
 
-  e2e-matrix:
-    runs-on: larger-runner
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
-    needs: [yarn-build]
-    strategy:
-      matrix:
-        e2e-type: [cosmwasm, non-cosmwasm]
-    steps:
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 18
+  # e2e-matrix:
+  #   runs-on: larger-runner
+  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
+  #   needs: [yarn-build]
+  #   strategy:
+  #     matrix:
+  #       e2e-type: [cosmwasm, non-cosmwasm]
+  #   steps:
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
 
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha || github.sha }}
-          submodules: recursive
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+  #         submodules: recursive
 
-      - name: foundry-install
-        uses: foundry-rs/foundry-toolchain@v1
+  #     - name: foundry-install
+  #       uses: foundry-rs/foundry-toolchain@v1
 
-      - name: setup rust
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          profile: minimal
+  #     - name: setup rust
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         profile: minimal
 
-      - name: rust cache
-        uses: Swatinem/rust-cache@v2
-        with:
-          prefix-key: "v1-${{ runner.os }}-rust-cache"
-          shared-key: ${{ matrix.e2e-type }}
-          workspaces: |
-            ./rust
+  #     - name: rust cache
+  #       uses: Swatinem/rust-cache@v2
+  #       with:
+  #         prefix-key: "v1-${{ runner.os }}-rust-cache"
+  #         shared-key: ${{ matrix.e2e-type }}
+  #         workspaces: |
+  #           ./rust
 
-      - name: Free disk space
-        run: |
-          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf "/usr/local/share/boost"
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+  #     - name: Free disk space
+  #       run: |
+  #         # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf "/usr/local/share/boost"
+  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-      - name: Install mold linker
-        uses: rui314/setup-mold@v1
-        with:
-          mold-version: 2.0.0
-          make-default: true
+  #     - name: Install mold linker
+  #       uses: rui314/setup-mold@v1
+  #       with:
+  #         mold-version: 2.0.0
+  #         make-default: true
 
-      - name: yarn-cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            **/node_modules
-            .yarn
-          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}
+  #     - name: yarn-cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           **/node_modules
+  #           .yarn
+  #         key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}
 
-      - name: build-cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./*
-            !./rust
-          key: ${{ github.event.pull_request.head.sha || github.sha }}
+  #     - name: build-cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           ./*
+  #           !./rust
+  #         key: ${{ github.event.pull_request.head.sha || github.sha }}
 
-      - name: Checkout registry
-        uses: ./.github/actions/checkout-registry
+  #     - name: Checkout registry
+  #       uses: ./.github/actions/checkout-registry
 
-      - name: agent tests with CosmWasm
-        run: cargo test --release --package run-locally --bin run-locally --features cosmos test-utils -- cosmos::test --nocapture
-        if: matrix.e2e-type == 'cosmwasm'
-        working-directory: ./rust
-        env:
-          RUST_BACKTRACE: 'full'
+  #     - name: agent tests with CosmWasm
+  #       run: cargo test --release --package run-locally --bin run-locally --features cosmos test-utils -- cosmos::test --nocapture
+  #       if: matrix.e2e-type == 'cosmwasm'
+  #       working-directory: ./rust
+  #       env:
+  #         RUST_BACKTRACE: 'full'
 
-      - name: agent tests excluding CosmWasm
-        run: cargo run --release --bin run-locally --features test-utils
-        if: matrix.e2e-type == 'non-cosmwasm'
-        working-directory: ./rust
-        env:
-          E2E_CI_MODE: 'true'
-          E2E_CI_TIMEOUT_SEC: '600'
-          E2E_KATHY_MESSAGES: '20'
-          RUST_BACKTRACE: 'full'
+  #     - name: agent tests excluding CosmWasm
+  #       run: cargo run --release --bin run-locally --features test-utils
+  #       if: matrix.e2e-type == 'non-cosmwasm'
+  #       working-directory: ./rust
+  #       env:
+  #         E2E_CI_MODE: 'true'
+  #         E2E_CI_TIMEOUT_SEC: '600'
+  #         E2E_KATHY_MESSAGES: '20'
+  #         RUST_BACKTRACE: 'full'
 
-  e2e:
-    runs-on: ubuntu-latest
-    needs: [e2e-matrix]
-    if: always() # This ensures that the job runs even if the e2e jobs fail
-    steps:
-      - name: Report Matrix Result
-        run: |
-          echo "All e2e-matrix jobs have completed."
-          # You can add additional commands here to report the result as needed
+  # e2e:
+  #   runs-on: ubuntu-latest
+  #   needs: [e2e-matrix]
+  #   if: always() # This ensures that the job runs even if the e2e jobs fail
+  #   steps:
+  #     - name: Report Matrix Result
+  #       run: |
+  #         echo "All e2e-matrix jobs have completed."
+  #         # You can add additional commands here to report the result as needed
 
-  prebuild-cli-e2e:
-    runs-on: larger-runner
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha || github.sha }}
-          submodules: recursive
+  # prebuild-cli-e2e:
+  #   runs-on: larger-runner
+  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+  #         submodules: recursive
 
-      - name: setup rust
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          profile: minimal
+  #     - name: setup rust
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         profile: minimal
 
-      - name: rust cache
-        uses: Swatinem/rust-cache@v2
-        with:
-          prefix-key: "v1-${{ runner.os }}-rust-cache"
-          shared-key: "cli-e2e"
-          workspaces: |
-            ./rust
+  #     - name: rust cache
+  #       uses: Swatinem/rust-cache@v2
+  #       with:
+  #         prefix-key: "v1-${{ runner.os }}-rust-cache"
+  #         shared-key: "cli-e2e"
+  #         workspaces: |
+  #           ./rust
 
-      - name: Free disk space
-        run: |
-          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf "/usr/local/share/boost"
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+  #     - name: Free disk space
+  #       run: |
+  #         # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf "/usr/local/share/boost"
+  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-      - name: Install mold linker
-        uses: rui314/setup-mold@v1
-        with:
-          mold-version: 2.0.0
-          make-default: true
+  #     - name: Install mold linker
+  #       uses: rui314/setup-mold@v1
+  #       with:
+  #         mold-version: 2.0.0
+  #         make-default: true
 
-      - name: Build validator
-        run: cargo build --bin validator --features test-utils
-        working-directory: ./rust
-        env:
-          RUST_BACKTRACE: 'full'
+  #     - name: Build validator
+  #       run: cargo build --bin validator --features test-utils
+  #       working-directory: ./rust
+  #       env:
+  #         RUST_BACKTRACE: 'full'
 
-      - name: Build relayer
-        run: cargo build --bin relayer --features test-utils
-        working-directory: ./rust
-        env:
-          RUST_BACKTRACE: 'full'
+  #     - name: Build relayer
+  #       run: cargo build --bin relayer --features test-utils
+  #       working-directory: ./rust
+  #       env:
+  #         RUST_BACKTRACE: 'full'
 
-  cli-advanced-e2e:
-    runs-on: larger-runner
-    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
-    needs: [yarn-build, prebuild-cli-e2e]
-    strategy:
-      matrix:
-        include:
-          - test-type: preset_hook_enabled
-          - test-type: configure_hook_enabled
-          - test-type: pi_with_core_chain
-    steps:
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 18
+  # cli-advanced-e2e:
+  #   runs-on: larger-runner
+  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
+  #   needs: [yarn-build, prebuild-cli-e2e]
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - test-type: preset_hook_enabled
+  #         - test-type: configure_hook_enabled
+  #         - test-type: pi_with_core_chain
+  #   steps:
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version: 18
 
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha || github.sha }}
-          submodules: recursive
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+  #         submodules: recursive
 
-      - name: foundry-install
-        uses: foundry-rs/foundry-toolchain@v1
+  #     - name: foundry-install
+  #       uses: foundry-rs/foundry-toolchain@v1
 
-      - name: setup rust
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          profile: minimal
+  #     - name: setup rust
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         profile: minimal
 
-      - name: rust cache
-        uses: Swatinem/rust-cache@v2
-        with:
-          prefix-key: "v1-${{ runner.os }}-rust-cache"
-          shared-key: "cli-e2e"
-          workspaces: |
-            ./rust
+  #     - name: rust cache
+  #       uses: Swatinem/rust-cache@v2
+  #       with:
+  #         prefix-key: "v1-${{ runner.os }}-rust-cache"
+  #         shared-key: "cli-e2e"
+  #         workspaces: |
+  #           ./rust
 
-      - name: Free disk space
-        run: |
-          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf "/usr/local/share/boost"
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+  #     - name: Free disk space
+  #       run: |
+  #         # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf "/usr/local/share/boost"
+  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-      - name: Install mold linker
-        uses: rui314/setup-mold@v1
-        with:
-          mold-version: 2.0.0
-          make-default: true
+  #     - name: Install mold linker
+  #       uses: rui314/setup-mold@v1
+  #       with:
+  #         mold-version: 2.0.0
+  #         make-default: true
 
-      - name: yarn-cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            **/node_modules
-            .yarn
-          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}
+  #     - name: yarn-cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           **/node_modules
+  #           .yarn
+  #         key: ${{ runner.os }}-yarn-cache-${{ hashFiles('./yarn.lock') }}
 
-      - name: build-cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ./*
-            !./rust
-          key: ${{ github.event.pull_request.head.sha || github.sha }}
+  #     - name: build-cache
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: |
+  #           ./*
+  #           !./rust
+  #         key: ${{ github.event.pull_request.head.sha || github.sha }}
 
-      - name: Checkout registry
-        uses: ./.github/actions/checkout-registry
+  #     - name: Checkout registry
+  #       uses: ./.github/actions/checkout-registry
 
-      - name: cli e2e tests
-        run: ./typescript/cli/ci-advanced-test.sh ${{ matrix.test-type }}
+  #     - name: cli e2e tests
+  #       run: ./typescript/cli/ci-advanced-test.sh ${{ matrix.test-type }}
 
   env-test:
     runs-on: ubuntu-latest
