chore(ci): restored ci to its full impl

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -58,66 +58,66 @@ jobs:
       - name: syncpack
         run: yarn syncpack list-mismatches
 
-  # lint-prettier:
-  #   runs-on: ubuntu-latest
-  #   needs: [yarn-install]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
-  #         # check out full history
-  #         fetch-depth: 0
+  lint-prettier:
+    runs-on: ubuntu-latest
+    needs: [yarn-install]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          # check out full history
+          fetch-depth: 0
 
-  #     - name: yarn-cache
-  #       uses: buildjet/cache@v4
-  #       with:
-  #         path: |
-  #           **/node_modules
-  #           .yarn
-  #         key: ${{ runner.os }}-yarn-4.5.1-cache-${{ hashFiles('./yarn.lock') }}
-  #         fail-on-cache-miss: true
+      - name: yarn-cache
+        uses: buildjet/cache@v4
+        with:
+          path: |
+            **/node_modules
+            .yarn
+          key: ${{ runner.os }}-yarn-4.5.1-cache-${{ hashFiles('./yarn.lock') }}
+          fail-on-cache-miss: true
 
-  #     # Build required before linting or the intra-monorepo package cycle checking won't work
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      # Build required before linting or the intra-monorepo package cycle checking won't work
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: lint
-  #       run: yarn lint
+      - name: lint
+        run: yarn lint
 
-  #     - name: prettier
-  #       run: |
-  #         yarn prettier
-  #         CHANGES=$(git status -s)
-  #         if [[ ! -z $CHANGES ]]; then
-  #           echo "Changes found: $CHANGES"
-  #           exit 1
-  #         fi
+      - name: prettier
+        run: |
+          yarn prettier
+          CHANGES=$(git status -s)
+          if [[ ! -z $CHANGES ]]; then
+            echo "Changes found: $CHANGES"
+            exit 1
+          fi
 
-  # yarn-test:
-  #   runs-on: ubuntu-latest
-  #   needs: [yarn-install]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
-  #         submodules: recursive
-  #         fetch-depth: 0
+  yarn-test:
+    runs-on: ubuntu-latest
+    needs: [yarn-install]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          submodules: recursive
+          fetch-depth: 0
 
-  #     - name: foundry-install
-  #       uses: foundry-rs/foundry-toolchain@v1
+      - name: foundry-install
+        uses: foundry-rs/foundry-toolchain@v1
 
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: Checkout registry
-  #       uses: ./.github/actions/checkout-registry
+      - name: Checkout registry
+        uses: ./.github/actions/checkout-registry
 
-  #     - name: Unit Tests
-  #       run: yarn test:ci
+      - name: Unit Tests
+        run: yarn test:ci
 
   cli-install-test:
     runs-on: ubuntu-latest
@@ -204,217 +204,217 @@ jobs:
           echo "CLI E2E tests failed"
           exit 1
 
-  # agent-configs:
-  #   runs-on: ubuntu-latest
-  #   needs: [yarn-install]
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       environment: [mainnet3, testnet4]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
-  #         fetch-depth: 0
+  agent-configs:
+    runs-on: ubuntu-latest
+    needs: [yarn-install]
+    strategy:
+      fail-fast: false
+      matrix:
+        environment: [mainnet3, testnet4]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          fetch-depth: 0
 
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: Checkout registry
-  #       uses: ./.github/actions/checkout-registry
+      - name: Checkout registry
+        uses: ./.github/actions/checkout-registry
 
-  #     - name: Generate ${{ matrix.environment }} agent config
-  #       run: |
-  #         cd typescript/infra
-  #         yarn tsx ./scripts/agents/update-agent-config.ts -e ${{ matrix.environment }}
-  #         CHANGES=$(git status -s)
-  #         if [[ ! -z $CHANGES ]]; then
-  #           echo "Changes found in agent config: $CHANGES"
-  #           exit 1
-  #         fi
+      - name: Generate ${{ matrix.environment }} agent config
+        run: |
+          cd typescript/infra
+          yarn tsx ./scripts/agents/update-agent-config.ts -e ${{ matrix.environment }}
+          CHANGES=$(git status -s)
+          if [[ ! -z $CHANGES ]]; then
+            echo "Changes found in agent config: $CHANGES"
+            exit 1
+          fi
 
-  # e2e-matrix:
-  #   runs-on: buildjet-8vcpu-ubuntu-2204
-  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
-  #   needs: [yarn-install]
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       e2e-type: [cosmwasm, evm, sealevel]
-  #   steps:
-  #     - uses: actions/setup-node@v4
-  #       with:
-  #         node-version: 18
+  e2e-matrix:
+    runs-on: buildjet-8vcpu-ubuntu-2204
+    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.base_ref == 'main' || github.base_ref == 'cli-2.0') || github.event_name == 'merge_group'
+    needs: [yarn-install]
+    strategy:
+      fail-fast: false
+      matrix:
+        e2e-type: [cosmwasm, evm, sealevel]
+    steps:
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 18
 
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
-  #         submodules: recursive
-  #         fetch-depth: 0
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          submodules: recursive
+          fetch-depth: 0
 
-  #     - name: foundry-install
-  #       uses: foundry-rs/foundry-toolchain@v1
+      - name: foundry-install
+        uses: foundry-rs/foundry-toolchain@v1
 
-  #     - name: setup rust
-  #       uses: dtolnay/rust-toolchain@stable
+      - name: setup rust
+        uses: dtolnay/rust-toolchain@stable
 
-  #     - name: rust cache
-  #       uses: Swatinem/rust-cache@v2
-  #       with:
-  #         prefix-key: 'v2-rust-e2e'
-  #         shared-key: ${{ matrix.e2e-type }}
-  #         cache-provider: 'buildjet'
-  #         save-if: ${{ !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}
-  #         workspaces: |
-  #           ./rust/main
-  #           ${{ matrix.e2e-type == 'sealevel' && './rust/sealevel' || '' }}
+      - name: rust cache
+        uses: Swatinem/rust-cache@v2
+        with:
+          prefix-key: 'v2-rust-e2e'
+          shared-key: ${{ matrix.e2e-type }}
+          cache-provider: 'buildjet'
+          save-if: ${{ !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}
+          workspaces: |
+            ./rust/main
+            ${{ matrix.e2e-type == 'sealevel' && './rust/sealevel' || '' }}
 
-  #     - name: Free disk space
-  #       run: |
-  #         # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
-  #         sudo rm -rf /usr/share/dotnet
-  #         sudo rm -rf /opt/ghc
-  #         sudo rm -rf "/usr/local/share/boost"
-  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Free disk space
+        run: |
+          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
 
-  #     - name: Install mold linker
-  #       uses: rui314/setup-mold@v1
-  #       with:
-  #         mold-version: 2.0.0
-  #         make-default: true
+      - name: Install mold linker
+        uses: rui314/setup-mold@v1
+        with:
+          mold-version: 2.0.0
+          make-default: true
 
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: Install system dependencies
-  #       run: |
-  #         sudo apt-get update -qq
-  #         sudo apt-get install -qq -y libudev-dev pkg-config protobuf-compiler
+      - name: Install system dependencies
+        run: |
+          sudo apt-get update -qq
+          sudo apt-get install -qq -y libudev-dev pkg-config protobuf-compiler
 
-  #     - name: Checkout registry
-  #       uses: ./.github/actions/checkout-registry
+      - name: Checkout registry
+        uses: ./.github/actions/checkout-registry
 
-  #     - name: Check for Rust file changes
-  #       id: check-rust-changes
-  #       run: |
-  #         if [[ -n "$(git diff ${{ github.event.pull_request.head.sha || github.sha }} ${{ github.event.pull_request.base.sha }} -- ./rust)" ]]; then
-  #           echo "rust_changes=true" >> $GITHUB_OUTPUT
-  #           echo "$(git diff ${{ github.event.pull_request.head.sha || github.sha }} ${{ github.event.pull_request.base.sha }} -- ./rust)"
-  #         else
-  #           echo "rust_changes=false" >> $GITHUB_OUTPUT
-  #         fi
+      - name: Check for Rust file changes
+        id: check-rust-changes
+        run: |
+          if [[ -n "$(git diff ${{ github.event.pull_request.head.sha || github.sha }} ${{ github.event.pull_request.base.sha }} -- ./rust)" ]]; then
+            echo "rust_changes=true" >> $GITHUB_OUTPUT
+            echo "$(git diff ${{ github.event.pull_request.head.sha || github.sha }} ${{ github.event.pull_request.base.sha }} -- ./rust)"
+          else
+            echo "rust_changes=false" >> $GITHUB_OUTPUT
+          fi
 
-  #     - name: agent tests (CosmWasm)
-  #       run: cargo test --release --package run-locally --bin run-locally --features cosmos -- cosmos::test --nocapture
-  #       if: ${{ matrix.e2e-type == 'cosmwasm' && steps.check-rust-changes.outputs.rust_changes == 'true' }}
-  #       working-directory: ./rust/main
-  #       env:
-  #         RUST_BACKTRACE: 'full'
+      - name: agent tests (CosmWasm)
+        run: cargo test --release --package run-locally --bin run-locally --features cosmos -- cosmos::test --nocapture
+        if: ${{ matrix.e2e-type == 'cosmwasm' && steps.check-rust-changes.outputs.rust_changes == 'true' }}
+        working-directory: ./rust/main
+        env:
+          RUST_BACKTRACE: 'full'
 
-  #     - name: agent tests (EVM)
-  #       run: cargo run --release --bin run-locally --features test-utils
-  #       if: ${{ matrix.e2e-type == 'evm' }}
-  #       working-directory: ./rust/main
-  #       env:
-  #         E2E_CI_MODE: 'true'
-  #         E2E_CI_TIMEOUT_SEC: '600'
-  #         E2E_KATHY_MESSAGES: '20'
-  #         RUST_BACKTRACE: 'full'
+      - name: agent tests (EVM)
+        run: cargo run --release --bin run-locally --features test-utils
+        if: ${{ matrix.e2e-type == 'evm' }}
+        working-directory: ./rust/main
+        env:
+          E2E_CI_MODE: 'true'
+          E2E_CI_TIMEOUT_SEC: '600'
+          E2E_KATHY_MESSAGES: '20'
+          RUST_BACKTRACE: 'full'
 
-  #     - name: agent tests (Sealevel)
-  #       run: cargo test --release --package run-locally --bin run-locally --features sealevel -- sealevel::test --nocapture
-  #       if: ${{ matrix.e2e-type == 'sealevel' && steps.check-rust-changes.outputs.rust_changes == 'true' }}
-  #       working-directory: ./rust/main
-  #       env:
-  #         E2E_CI_MODE: 'true'
-  #         E2E_CI_TIMEOUT_SEC: '600'
-  #         RUST_BACKTRACE: 'full'
+      - name: agent tests (Sealevel)
+        run: cargo test --release --package run-locally --bin run-locally --features sealevel -- sealevel::test --nocapture
+        if: ${{ matrix.e2e-type == 'sealevel' && steps.check-rust-changes.outputs.rust_changes == 'true' }}
+        working-directory: ./rust/main
+        env:
+          E2E_CI_MODE: 'true'
+          E2E_CI_TIMEOUT_SEC: '600'
+          RUST_BACKTRACE: 'full'
 
-  # e2e:
-  #   runs-on: ubuntu-latest
-  #   needs: e2e-matrix
-  #   if: always()
-  #   steps:
-  #     - name: Check e2e matrix status
-  #       if: ${{ needs.e2e-matrix.result != 'success' }}
-  #       run: |
-  #         echo "E2E tests failed"
-  #         exit 1
+  e2e:
+    runs-on: ubuntu-latest
+    needs: e2e-matrix
+    if: always()
+    steps:
+      - name: Check e2e matrix status
+        if: ${{ needs.e2e-matrix.result != 'success' }}
+        run: |
+          echo "E2E tests failed"
+          exit 1
 
-  # env-test:
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     MAINNET3_ARBITRUM_RPC_URLS: ${{ secrets.MAINNET3_ARBITRUM_RPC_URLS }}
-  #     MAINNET3_OPTIMISM_RPC_URLS: ${{ secrets.MAINNET3_OPTIMISM_RPC_URLS }}
-  #     MAINNET3_ETHEREUM_RPC_URLS: ${{ secrets.MAINNET3_ETHEREUM_RPC_URLS }}
-  #     TESTNET4_SEPOLIA_RPC_URLS: ${{ secrets.TESTNET4_SEPOLIA_RPC_URLS }}
+  env-test:
+    runs-on: ubuntu-latest
+    env:
+      MAINNET3_ARBITRUM_RPC_URLS: ${{ secrets.MAINNET3_ARBITRUM_RPC_URLS }}
+      MAINNET3_OPTIMISM_RPC_URLS: ${{ secrets.MAINNET3_OPTIMISM_RPC_URLS }}
+      MAINNET3_ETHEREUM_RPC_URLS: ${{ secrets.MAINNET3_ETHEREUM_RPC_URLS }}
+      TESTNET4_SEPOLIA_RPC_URLS: ${{ secrets.TESTNET4_SEPOLIA_RPC_URLS }}
 
-  #   timeout-minutes: 10
-  #   needs: [yarn-install]
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       environment: [mainnet3]
-  #       chain: [ethereum, arbitrum, optimism, inevm]
-  #       module: [core, igp]
-  #       include:
-  #         - environment: testnet4
-  #           chain: sepolia
-  #           module: core
+    timeout-minutes: 10
+    needs: [yarn-install]
+    strategy:
+      fail-fast: false
+      matrix:
+        environment: [mainnet3]
+        chain: [ethereum, arbitrum, optimism, inevm]
+        module: [core, igp]
+        include:
+          - environment: testnet4
+            chain: sepolia
+            module: core
 
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: foundry-install
-  #       uses: foundry-rs/foundry-toolchain@v1
+      - name: foundry-install
+        uses: foundry-rs/foundry-toolchain@v1
 
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: Checkout registry
-  #       uses: ./.github/actions/checkout-registry
+      - name: Checkout registry
+        uses: ./.github/actions/checkout-registry
 
-  #     - name: Fork test ${{ matrix.environment }} ${{ matrix.module }} ${{ matrix.chain }} deployment with retries
-  #       uses: nick-fields/retry@v3
-  #       with:
-  #         timeout_minutes: 8
-  #         max_attempts: 3
-  #         retry_wait_seconds: 30
-  #         command: cd typescript/infra && ./fork.sh ${{ matrix.environment }} ${{ matrix.module }} ${{ matrix.chain }}
-  #         on_retry_command: |
-  #           echo "Test failed, waiting before retry..."
+      - name: Fork test ${{ matrix.environment }} ${{ matrix.module }} ${{ matrix.chain }} deployment with retries
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 8
+          max_attempts: 3
+          retry_wait_seconds: 30
+          command: cd typescript/infra && ./fork.sh ${{ matrix.environment }} ${{ matrix.module }} ${{ matrix.chain }}
+          on_retry_command: |
+            echo "Test failed, waiting before retry..."
 
-  # coverage:
-  #   runs-on: ubuntu-latest
-  #   needs: [yarn-install]
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
-  #         fetch-depth: 0
+  coverage:
+    runs-on: ubuntu-latest
+    needs: [yarn-install]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          fetch-depth: 0
 
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: foundry-install
-  #       uses: foundry-rs/foundry-toolchain@v1
+      - name: foundry-install
+        uses: foundry-rs/foundry-toolchain@v1
 
-  #     - name: Run tests with coverage
-  #       run: yarn coverage
-  #       env:
-  #         NODE_OPTIONS: --max_old_space_size=4096
+      - name: Run tests with coverage
+        run: yarn coverage
+        env:
+          NODE_OPTIONS: --max_old_space_size=4096
 
-  #     - name: Upload coverage reports to Codecov with GitHub Action
-  #       uses: codecov/codecov-action@v4
-  #       with:
-  #         token: ${{ secrets.CODECOV_TOKEN }}
+      - name: Upload coverage reports to Codecov with GitHub Action
+        uses: codecov/codecov-action@v4
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
