refactor(ci): updated the cli e2e tests to use the built cli if running in the ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -137,65 +137,72 @@ jobs:
       - name: Test run the CLI
         run: hyperlane --version
 
-  # cli-e2e-matrix:
-  #   runs-on: ubuntu-latest
-  #   needs:
-  #     - yarn-install
-  #     - cli-install-test
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       test:
-  #         # Core Commands
-  #         - core-apply
-  #         - core-check
-  #         - core-deploy
-  #         - core-init
-  #         - core-read
-  #         # Other commands
-  #         - relay
-  #         # Warp Commands
-  #         - warp-apply
-  #         - warp-apply-extend
-  #         - warp-check
-  #         - warp-bridge-1
-  #         - warp-bridge-2
-  #         - warp-init
-  #         - warp-read
-  #         - warp-send
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
-  #         submodules: recursive
-  #         fetch-depth: 0
+  cli-e2e-matrix:
+    runs-on: ubuntu-latest
+    needs:
+      - yarn-install
+      - cli-install-test
+    strategy:
+      fail-fast: false
+      matrix:
+        test:
+          # Core Commands
+          - core-apply
+          - core-check
+          - core-deploy
+          - core-init
+          - core-read
+          # Other commands
+          - relay
+          # Warp Commands
+          - warp-apply
+          - warp-apply-extend
+          - warp-check
+          - warp-bridge-1
+          - warp-bridge-2
+          - warp-init
+          - warp-read
+          - warp-send
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          submodules: recursive
+          fetch-depth: 0
 
-  #     - name: foundry-install
-  #       uses: foundry-rs/foundry-toolchain@v1
+      - name: foundry-install
+        uses: foundry-rs/foundry-toolchain@v1
 
-  #     - name: yarn-build
-  #       uses: ./.github/actions/yarn-build-with-cache
-  #       with:
-  #         ref: ${{ github.event.pull_request.head.sha || github.sha }}
+      - name: yarn-build
+        uses: ./.github/actions/yarn-build-with-cache
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: Checkout registry
-  #       uses: ./.github/actions/checkout-registry
+      - name: install-hyperlane-cli
+        id: install-hyperlane-cli
+        uses: ./.github/actions/install-cli
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
 
-  #     - name: CLI e2e tests (${{ matrix.test }})
-  #       run: yarn --cwd typescript/cli test:e2e
-  #       env:
-  #         CLI_E2E_TEST: ${{ matrix.test }}
+      - name: Checkout registry
+        uses: ./.github/actions/checkout-registry
 
-  # cli-e2e:
-  #   runs-on: ubuntu-latest
-  #   needs: cli-e2e-matrix
-  #   if: always()
-  #   steps:
-  #     - name: Check cli-e2e matrix status
-  #       if: ${{ needs.cli-e2e-matrix.result != 'success' }}
-  #       run: |
-  #         echo "CLI E2E tests failed"
-  #         exit 1
+      - name: CLI e2e tests (${{ matrix.test }})
+        run: yarn --cwd typescript/cli test:e2e
+        env:
+          CLI_E2E_TEST: ${{ matrix.test }}
+          IS_CI: true
+
+  cli-e2e:
+    runs-on: ubuntu-latest
+    needs: cli-e2e-matrix
+    if: always()
+    steps:
+      - name: Check cli-e2e matrix status
+        if: ${{ needs.cli-e2e-matrix.result != 'success' }}
+        run: |
+          echo "CLI E2E tests failed"
+          exit 1
 
   # agent-configs:
   #   runs-on: ubuntu-latest
