conditionally run cli-e2e/yarn-test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -104,12 +104,11 @@ jobs:
         run: |
           rm -f changed_files.txt
 
-  yarn-test:
+  rust-only:
+    if: github.event_name == 'pull_request'
+    outputs:
+      only_rust: ${{ steps.check-rust-only.outputs.only_rust }}
     runs-on: ubuntu-latest
-    needs: [yarn-install]
-    timeout-minutes: 10
-    env:
-      PR_BASE: ${{ github.base_ref }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -117,16 +116,38 @@ jobs:
           submodules: recursive
           fetch-depth: 0
 
+      - name: Fetch PR base
+        run: git fetch origin $PR_BASE
+
       - name: Check for Rust changes
+        id: check-rust-only
         run: |
           # Check for Rust changes
-          if git diff $PR_BASE...HEAD --name-only | grep -qE '^rust/'; then
+          if git diff origin/$PR_BASE...HEAD --name-only | grep -qE '^rust/'; then
             # Check if there are only Rust changes
-            if ! git diff $PR_BASE...HEAD --name-only | grep -qvE '^rust/'; then
-              echo "Only Rust changes detected. Exiting."
-              exit 0
+            if ! git diff origin/$PR_BASE...HEAD --name-only | grep -qvE '^rust/'; then
+              echo "only_rust=true" >> $GITHUB_OUTPUT
+              echo "Only Rust changes detected."
+            else
+              echo "only_rust=false" >> $GITHUB_OUTPUT
             fi
+          else
+            echo "only_rust=false" >> $GITHUB_OUTPUT
           fi
+
+  yarn-test-run:
+    runs-on: ubuntu-latest
+    needs: [rust-only]
+    timeout-minutes: 10
+    env:
+      PR_BASE: ${{ github.base_ref }}
+    if: needs.rust-only.outputs.only_rust == 'false'
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          submodules: recursive
+          fetch-depth: 0
 
       - name: foundry-install
         uses: foundry-rs/foundry-toolchain@v1
@@ -141,6 +162,25 @@ jobs:
 
       - name: Unit Tests
         run: yarn test:ci
+
+  yarn-test-fallback:
+    runs-on: ubuntu-latest
+    needs: [yarn-test-run]
+    if: needs.yarn-test-run.result == 'skipped'
+    steps:
+      - name: Fallback for Yarn Test
+        run: echo "Yarn Test was skipped, running fallback."
+
+  yarn-test:
+    runs-on: ubuntu-latest
+    needs: [yarn-test-run, yarn-test-fallback]
+    if: always()
+    steps:
+      - name: Check yarn-test status
+        if: ${{ needs.yarn-test-run.result != 'success' }}
+        run: |
+          echo "Yarn Test failed"
+          exit 1
 
   infra-test:
     runs-on: ubuntu-latest
@@ -163,15 +203,18 @@ jobs:
       - name: Checkout registry
         uses: ./.github/actions/checkout-registry
 
+      - name: Fetch PR base
+        run: git fetch origin $PR_BASE
+
       - name: Balance Tests
         run: |
-          if git diff $PR_BASE...HEAD --name-only | grep -qE '^typescript/infra/config/environments/mainnet3/balances|^.registryrc$'; then
+          if git diff origin/$PR_BASE...HEAD --name-only | grep -qE '^typescript/infra/config/environments/mainnet3/balances|^.registryrc$'; then
             yarn --cwd typescript/infra test:balance
           fi
 
       - name: Warp Config Tests
         run: |
-          if git diff $PR_BASE...HEAD --name-only | grep -qE '^typescript/infra/|^.registryrc$'; then
+          if git diff origin/$PR_BASE...HEAD --name-only | grep -qE '^typescript/infra/|^.registryrc$'; then
             yarn --cwd typescript/infra test:warp
           fi
 
@@ -193,6 +236,8 @@ jobs:
 
   cli-e2e-matrix:
     runs-on: ubuntu-latest
+    needs: [rust-only]
+    if: needs.rust-only.outputs.only_rust == 'false'
     strategy:
       fail-fast: false
       matrix:
@@ -245,9 +290,17 @@ jobs:
         env:
           CLI_E2E_TEST: ${{ matrix.test }}
 
+  cli-e2e-fallback:
+    runs-on: ubuntu-latest
+    needs: [cli-e2e-matrix]
+    if: needs.cli-e2e-matrix.result == 'skipped'
+    steps:
+      - name: Fallback for CLI E2E
+        run: echo "CLI E2E Matrix was skipped, running fallback."
+
   cli-e2e:
     runs-on: ubuntu-latest
-    needs: cli-e2e-matrix
+    needs: [cli-e2e-matrix, cli-e2e-fallback]
     if: always()
     steps:
       - name: Check cli-e2e matrix status
